# Generated by Django 3.2.9 on 2022-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_book_slug'),
        ('bookshelf', '0002_auto_20220129_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='books',
            field=models.ManyToManyField(to='shop.Book'),
        ),
    ]
