# Generated by Django 3.2.9 on 2022-01-29 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_remove_book_slug'),
        ('bookshelf', '0003_alter_bookshelf_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBook',
            new_name='RatedBook',
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='rated_books',
            field=models.ManyToManyField(to='bookshelf.RatedBook'),
        ),
    ]
