# Generated by Django 3.2.9 on 2022-01-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0007_rename_book_shelfbook_mother_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='rated_books',
        ),
    ]
