# Generated by Django 3.2.9 on 2022-01-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0008_remove_bookshelf_rated_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatedBook',
        ),
    ]
