version: "3.8"
services:
  bookstore:
    build: .
    volumes:
      - .:/bookstore
    ports:
      - 8000:8000
    image: bookstore:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000