# Generated by Django 3.2.9 on 2022-01-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='cool books awfwafafwaf', max_length=500),
            preserve_default=False,
        ),
    ]
