# Generated by Django 3.2.9 on 2022-01-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
