# Generated by Django 3.2.9 on 2022-01-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ratings_sum',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='user_ratings_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
