# Generated by Django 3.2.9 on 2022-01-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220130_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ratings_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='user_ratings_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
